# Generated by Django 6.0.4 on 2026-05-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address_book", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
